gebiete:
  gebiet1:
    slot: 0
    item: DIAMOND_SWORD
    name: "&bTest"
    lore:
      - "&7Testtest"
      - "&7Klicke zum Teleportieren"
    x: -19
    y: 50
    z: 31
    world: world

  gebiet2:
    slot: 1
    item: APPLE
    name: "&cApfelland"
    lore:
      - "&7Ein Land voller Äpfel"
      - "&7Klicke zum Teleportieren"
    x: 100
    y: 70
    z: 100
    world: world