# This is the main configuration file for the plugin.

#Gebiete
gebiete:
  gebiet1:
    slot: 0
    item: DIAMOND_SWORD
    name: "&bTest"
    lore:
      - "&7Testtest"
      - "&7Klicke zum Teleportieren"
    x: -19
    y: 50
    z: 31
    world: world

  gebiet2:
    slot: 1
    item: APPLE
    name: "&cApfelland"
    lore:
      - "&7Ein Land voller Äpfel"
      - "&7Klicke zum Teleportieren"
    x: 100
    y: 70
    z: 100
    world: world


#Items
items:
  gold_rank:
    slot: 0
    item: GOLD_BLOCK
    name: "&e&lGOLD RANG"
    lore:
      - "§cDieser Kostet 101010$"
  fly_permission:
    slot: 1
    item: GREEN_DYE
    name: "&7/fly"
    lore:
      - "§cDamit kannst du Fliegen."

